name: oic-model-server
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - plotly
  - sqlalchemy
  - fastapi
  - uvicorn
  - pydantic  
  - sqlmodel
  - pydantic-settings
  - psycopg2
  - geopandas
  - folium
  - fiona  
  - requests
  - streamlit
  - jupyter
  - pip
  - joblib
  - python-multipart
  - geoalchemy2
  - sphinx
  - sphinx-rtd-theme
  - sphinx-autodoc-typehints
  - sphinx-copybutton