services:
  oic-model-postgis:
    image: postgis/postgis:15-3.5
    container_name: oic-model-postgis
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - oic-db-model-service-dev:/var/lib/postgresql/data
    networks:
      - oic_service_network_dev

  oic-model-api:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.api
    image: oic-model-api-dev
    container_name: oic-model-api-dev
    depends_on:
      oic-model-postgis:
        condition: service_started
    env_file:
      - ../.env
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@oic-model-postgis:5432/postgres}
    volumes:
      - ..:/mini-proyecto-oic
    ports:
      - "8000:8000"
      - "5678:5678"      
    networks:
      - oic_service_network_dev

  oic-ui-service:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.ui
    image: oic-model-ui-dev
    container_name: oic-model-ui-dev
    depends_on:
      oic-model-api:
        condition: service_started
    env_file:
      - ../.env
    environment:
      - PYTHONUNBUFFERED=1
      - API_URL=http://oic-model-api:8000
      - STREAMLIT_SERVER_RUN_ON_SAVE=true
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_BROWSER_SERVER_ADDRESS=0.0.0.0
    ports:
      - "8501:8501"
      - "5679:5679"
    volumes:
      - ..:/mini-proyecto-oic
    networks:
      - oic_service_network_dev
    
volumes:
  oic-db-model-service-dev:

networks:
  oic_service_network_dev:
    driver: bridge
